repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
    #files: (automation/|ci/|code-scanning/|deployments/|pages/).*(yaml|yml|json)$
    files: (.github/|profile/|workflow-templates/).*(yaml|yml|json)$
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-json
  - id: check-yaml
