name: experiment with GitHub CLI in Actions

# https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/using-github-cli-in-workflows

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_REPO: ${{ github.repository }}


jobs:
  list-repo-topics:
    runs-on: ubuntu-latest
    steps:
      - name: retrieve list of repo topics
        run: |
          repoTopicList=$(gh api repos/$GH_REPO/topics)
          echo 'REPO_TOPIC_LIST='$repoTopicList >> $GITHUB_ENV
      - name: retrieve list of repo languages
        run: |
          repoLanguageList=$(gh api repos/$GH_REPO/languages)
          echo 'REPO_LANGUAGE_LIST'=$repoLanguageList >> $GITHUB_ENV
      - name: display environment variables
        run: |
          printenv
