name: experiment with GitHub CLI in Actions

# https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/using-github-cli-in-workflows

on:
  workflow_dispatch:

jobs:
  list-repo-topics:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh api repos/{owner}/{repo}/topics
        env:
          GH_TOKEN: ${{ secrets.GH_ORG_BEST_FAMILY_REPOS_READ }}
