name: experiment with GitHub CLI in Actions

# https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/using-github-cli-in-workflows

on:
  workflow_dispatch:

jobs:
  list-repo-topics:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          gh api repos/$GH_REPO/topics
