name: workflow github api learning

on:
  workflow_dispatch:

jobs:
  retrieve-context:
    name: learning steps
    runs-on: ubuntu-latest
    steps:
      # examples: https://github.com/actions/github-script#examples
      # lets output all the contents of the context
      - name: Display all context attributes
        uses: actions/github-script@v7.0.1
        with:
          script: console.log(context)

      # example of how to read a step result and display it
      - uses: actions/github-script@v7.0.1
        id: set-result
        with:
          script: return "Hello!"
          result-encoding: string
      - name: Display result
        run: echo "${{steps.set-result.outputs.result}}"

      # example to retrieve and display repo issues
      - uses: actions/github-script@v7
        id: get-issues
        with:
          script: |
            github.rest.issues.get({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
      - name: Display repo topics
        run: echo "${{steps.get-issues.outputs.result}}"

      # my ultimate goal is to read the repo topics for reuse in a later step
      - name: Get repo topics
        id: get-repo-topics
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const alltopics = await github.rest.repos.getAllTopics({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            return alltopics
      - name: Display repo topics
        run: echo "${{steps.get-repo-topics.outputs.result}}"
