name: 'Sync labels'
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - .github/labels.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Build and store list of repos in ${{github.repository_owner}}
        run: |
          REPO_LIST=($(gh repo list ${{github.repository_owner}}))
          echo "$REPO_LIST" >> "$GITHUB_ENV"
      - name: Display env output
        run: env | sort -rn
      - uses: micnncim/action-label-syncer@v1.3.0
        with:
          manifest: .github/labels.yml
          repository: |

          token: ${{ secrets.GH_ORG_BEST_FAMILY_PROJECTS_ADMIN }}
